/* AUTO-GENERATED by onchain/scripts/deploy.js. Holds every deployed
   network; the terminal lets users switch between them (see setNetwork). */
export const NETWORKS = {
  mainnet: {
    enabled: true,
    chainId: 4663,
    chainName: "Robinhood Chain",
    rpc: "https://rpc.mainnet.chain.robinhood.com",
    explorer: "https://explorer.chain.robinhood.com",
    mockUsd: "0x5fc5360D0400a0Fd4f2af552ADD042D716F1d168",
    collateralSymbol: "USDG",
    collateralHasFaucet: false,
    oracle: "0x210c57069dc35dba8839F247922B8D1Fa265418a",
    vault: "0x7D399CC5dF5a00edb8c9572433B8Ed53ca38AfeC",
  },
  testnet: {
    enabled: true,
    chainId: 46630,
    chainName: "Robinhood Chain Testnet",
    rpc: "https://rpc.testnet.chain.robinhood.com",
    explorer: "https://explorer.testnet.chain.robinhood.com",
    mockUsd: "0x0bdD4bc15c53829433d1DD1282520fB6F7f58Ddc",
    collateralSymbol: "mUSD",
    collateralHasFaucet: true,
    oracle: "0xd1cab599bdD8d4C1C7D1e514423128ccC4f22F3E",
    vault: "0xD3c2eACe35799076D50Ca89A575D80c23F6F5f95",
  },
};

const NKEY = 'miraukin_network';
/** The user-selected network key, defaulting to mainnet (live/real USDG). */
export function activeNetwork() {
  try { const v = localStorage.getItem(NKEY); if (v && NETWORKS[v] && NETWORKS[v].enabled) return v; } catch (_) {}
  return NETWORKS.mainnet && NETWORKS.mainnet.enabled ? 'mainnet' : 'testnet';
}
export function setNetwork(n) { try { localStorage.setItem(NKEY, n); } catch (_) {} }

// Active config consumed by js/onchain.js. Switching network + reloading swaps it.
export const ONCHAIN = NETWORKS[activeNetwork()] || { enabled: false };
